version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000" # Exposing port 3000 to the host machine
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development # Setting the environment variable for development
    command: ["npx", "nodemon", "--config", "/usr/src/app/nodemon.json"]
    restart: unless-stopped
